In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 90.7 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [3]:
[[1, 2],[3, 4]] + [[5, 6],[7, 8]]

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [7]:
a = np.array([[1, 2],
              [3, 4]])
# print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
print(a * b) 
print(a @ b) 

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [8]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열

[[140]
 [320]]


In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]
